name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Lint code
      run: npm run lint
    
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID || '83c5a5f5e1b745cde3ae5be39b6b6f4e' }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret-for-ci' }}
        NEXTAUTH_URL: http://localhost:3000
    
    - name: Run Playwright tests
      run: npm run test:ci
      env:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID || '83c5a5f5e1b745cde3ae5be39b6b6f4e' }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret-for-ci' }}
        NEXTAUTH_URL: http://localhost:3000
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy-check:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Vercel deployment simulation
      run: npm run build
      env:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID || '83c5a5f5e1b745cde3ae5be39b6b6f4e' }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'vercel-compatible-secret' }}
        NEXTAUTH_URL: https://w3rk.net
    
    - name: Check build output
      run: |
        echo "Checking build output..."
        ls -la .next/
        echo "Build completed successfully ✅"
